import SwiftUI

// ============================================================
// MARK: - Subject
// ============================================================

struct Subject: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var name: String
    var colorHex: String
    var emoji: String           // kept for backwards compatibility with existing views

    var color: Color { Color(hex: colorHex) ?? StudyTheme.accent }

    static let presets: [Subject] = [
        Subject(name: "Mathematics",  colorHex: "#4A8EFF", emoji: "📐"),
        Subject(name: "Physics",      colorHex: "#FF6B3D", emoji: "⚛️"),
        Subject(name: "Programming",  colorHex: "#9B6DFF", emoji: "💻"),
        Subject(name: "English",      colorHex: "#00C875", emoji: "📖"),
        Subject(name: "History",      colorHex: "#FFC433", emoji: "🏛️"),
    ]

    static let colorOptions: [String] = [
        "#4A8EFF", "#FF6B3D", "#9B6DFF", "#00C875", "#FFC433",
        "#FF4D6D", "#00B4D8", "#06D6A0", "#FF9F1C", "#E040FB"
    ]
}

// ============================================================
// MARK: - Chat Message
// ============================================================

struct ChatMessage: Identifiable {
    let id      = UUID()
    let role: String        // "user" | "assistant"
    let content: String
    let date: Date = Date()
}

// ============================================================
// MARK: - Quiz
// ============================================================

/// A single multiple-choice question generated by the AI.
struct QuizQuestion: Identifiable, Codable {
    var id: UUID = UUID()
    var question: String
    var options: [String]       // always 4 items (A / B / C / D)
    var correctIndex: Int       // 0 – 3
    var explanation: String
    var difficulty: Difficulty

    enum Difficulty: String, Codable, CaseIterable {
        case beginner, intermediate, advanced

        var label: String {
            switch self {
            case .beginner:     return "Beginner"
            case .intermediate: return "Intermediate"
            case .advanced:     return "Advanced"
            }
        }

        var color: Color {
            switch self {
            case .beginner:     return StudyTheme.shortBreakColor
            case .intermediate: return StudyTheme.warning
            case .advanced:     return StudyTheme.danger
            }
        }
    }
}

/// A completed or in-progress quiz attempt.
struct QuizSession: Identifiable, Codable {
    var id: UUID = UUID()
    var title: String
    var subject: String?
    var difficulty: QuizQuestion.Difficulty
    var questions: [QuizQuestion]
    /// Parallel array to `questions`. -1 means the question has not been answered yet.
    var userAnswers: [Int]
    var createdDate: Date = Date()
    var completedDate: Date?

    // MARK: Computed

    /// Number of correctly answered questions.
    var score: Int {
        zip(questions, userAnswers)
            .filter { question, answer in question.correctIndex == answer }
            .count
    }

    var totalQuestions: Int { questions.count }

    var percentage: Double {
        guard totalQuestions > 0 else { return 0 }
        return Double(score) / Double(totalQuestions)
    }

    var isCompleted: Bool { completedDate != nil }

    var isToday: Bool { Calendar.current.isDateInToday(createdDate) }

    var gradeLabel: String {
        switch percentage {
        case 0.9...:  return "Excellent"
        case 0.75...: return "Good"
        case 0.6...:  return "Fair"
        default:      return "Needs Review"
        }
    }

    var gradeColor: Color {
        switch percentage {
        case 0.9...:  return StudyTheme.success
        case 0.75...: return StudyTheme.accent
        case 0.6...:  return StudyTheme.warning
        default:      return StudyTheme.danger
        }
    }
}

// ============================================================
// MARK: - Flashcard
// ============================================================

/// A single flashcard with front (question/term) and back (answer/definition).
struct Flashcard: Identifiable, Codable {
    var id: UUID = UUID()
    var front: String
    var back: String
    var category: String
    var difficulty: QuizQuestion.Difficulty
    var reviewCount: Int  = 0
    var knewItCount: Int  = 0
    var lastReviewed: Date?

    var masteryPercent: Double {
        guard reviewCount > 0 else { return 0 }
        return Double(knewItCount) / Double(reviewCount)
    }

    var isMastered: Bool { reviewCount > 0 && masteryPercent >= 0.7 }
}

/// A named collection of flashcards on a single topic.
struct FlashcardDeck: Identifiable, Codable {
    var id: UUID = UUID()
    var title: String
    var subject: String?
    var cards: [Flashcard]
    var createdDate: Date      = Date()
    var lastReviewedDate: Date?

    // MARK: Computed

    var totalCards: Int { cards.count }

    var masteredCards: Int { cards.filter(\.isMastered).count }

    var overallMastery: Double {
        guard !cards.isEmpty else { return 0 }
        return Double(masteredCards) / Double(cards.count)
    }

    var isToday: Bool {
        guard let d = lastReviewedDate else { return false }
        return Calendar.current.isDateInToday(d)
    }

    var totalReviews: Int { cards.reduce(0) { $0 + $1.reviewCount } }
}

// ============================================================
// MARK: - Document Analysis
// ============================================================

/// Result of AI-powered analysis of a study document.
struct AnalyzedDocument: Identifiable, Codable {
    var id: UUID = UUID()
    var title: String
    var originalText: String
    var summary: String
    var keyConcepts: [String]
    var definitions: [String: String]   // term → definition
    var suggestedQuestions: [String]
    var subject: String?
    var analyzedDate: Date = Date()

    var isToday: Bool { Calendar.current.isDateInToday(analyzedDate) }

    /// Word count of the original text.
    var wordCount: Int { originalText.split(separator: " ").count }
}

// ============================================================
// MARK: - Color hex initialiser
// ============================================================

extension Color {
    init?(hex: String) {
        let h = hex.trimmingCharacters(in: .whitespacesAndNewlines)
                   .replacingOccurrences(of: "#", with: "")
        guard h.count == 6 else { return nil }
        var rgb: UInt64 = 0
        Scanner(string: h).scanHexInt64(&rgb)
        self.init(
            red:   Double((rgb >> 16) & 0xFF) / 255,
            green: Double((rgb >> 8)  & 0xFF) / 255,
            blue:  Double( rgb        & 0xFF) / 255
        )
    }
}

// ============================================================
// MARK: - Numeric helpers
// ============================================================

extension Int {
    /// Converts minutes to a human-readable string. e.g. 90 → "1h 30m"
    var minutesToHoursString: String {
        let h = self / 60
        let m = self % 60
        if h > 0 { return m > 0 ? "\(h)h \(m)m" : "\(h)h" }
        return "\(m)m"
    }
}

extension Double {
    /// 0.875 → "88%"
    var percentString: String { "\(Int((self * 100).rounded()))%" }
}
